myMovie-main/movie/urls.py
from django.urls import path
from .import views

app_name = 'movie'
urlpatterns = [
    path('', views.MovieListView.as_view(),name='home'),
    path('detail/<slug:slug>/', views.MovieDetailView.as_view(), name='detail'),
    path('search/', views.movieSearch, name='search'),

    path('like/<int:pk>', views.addLike, name='like')
]

myMovie-main/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

myMovie-main/movie/models.py
from django.db import models

# Create your models here.
class Rubrics(models.Model):
    name = models.CharField('Name', max_length=200)
    slug = models.SlugField('*', max_length=200, unique=True)
    
    class Meta:
        verbose_name_plural = 'Rubrics'

    def __str__(self):
        return str(self.name)

class Genre(models.Model):
    name = models.CharField('Name', max_length=200)
    slug = models.SlugField('*', max_length=200, unique=True)

    class Meta:
        verbose_name_plural = 'Genres'

    def __str__(self):
        return str(self.name)

    
class Movie(models.Model):
    title = models.CharField('Title', max_length=300)
    slug = models.SlugField('*', max_length=200, unique=True)
    rubric = models.ForeignKey(Rubrics,on_delete=models.CASCADE,related_name='rubric')
    genre = models.ManyToManyField('Genre', related_name='genres')
    poster = models.ImageField('Movie poster', upload_to='movie_posters/')
    description = models.TextField("Movie description",blank=True)
    director = models.CharField("Film director", max_length=100)
    actors = models.CharField('Film actors', max_length=200)
    year = models.PositiveIntegerField(default=0)
    country = models.CharField('Country', max_length=100)
    duration = models.CharField('Duration', max_length=100)
    like = models.PositiveIntegerField('Likes', default=0)
    dislike = models.PositiveIntegerField('DisLikes', default=0)

    class Meta:
        verbose_name_plural = 'Movies'

    def __str__(self):
        return str(self.title)

myMovie-main/movie/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse,JsonResponse
from django.views.generic import  (
    TemplateView,
    ListView,
    DetailView
    )
from .models import Rubrics, Movie
# Create your views here.
def get_all_rubrics(request):
    context = {
        'rubrics':Rubrics.objects.all()
    }
    return context

class MovieListView(ListView):
    model = Movie
    paginate_by = 8
    template_name = 'index.html'

class MovieDetailView(DetailView):
    model = Movie

    
import json
def movieSearch(request):
    data = {}
    query = request.GET.get('data')
    movies = list(Movie.objects.filter(slug__icontains=query).values())
    data['data'] = movies
    return JsonResponse(data)

def addLike(request, pk):
    print(type(pk))
    movie = Movie.objects.get(id=pk)
    movie.like += 1
    movie.save()
    return redirect('movie:detail',movie.slug)

myMovie-main/templates/movie/movie_detail.html
{% extends "../base.html" %}
{% load static %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="row">
               <div class="col s12 m3 l3">
                    <div class="card-panel z-depth-3">
                        <div class="header">
                        <h5>Rubrics</h5>
                        </div>
                       <div class="collection">
                           {% for rubric in rubrics  %}
                               <a href="#" class="collection-item">
                                  <b>{{ rubric.name|upper }}</b>
                               </a>
                           {% endfor %}
                       </div>
                    </div>

              </div>
            <div class="card col s12 m9 l9">
                <br>
                <div class="row">
                    <div class="col s6 m6">
                        <img src="{{ object.poster.url }}" class="responsive-img">
                    </div>
                    <div class="col s6 m6">
                        <ul class="collection with-header">
                            <li class="collection-header"><h5>Film information</h5></li>
                            <li class="collection-item">Title:  <b>{{ object.title }}</b></li>
                            <li class="collection-item">Rubric: <b>{{ object.rubric }}</b></li>
                            <li class="collection-item">Director: <b>{{ object.director }}</b></li>
                            <li class="collection-item">Year: <b>{{ object.year }}</b></li>
                            <li class="collection-item">Country: <b>{{ object.country}}</b></li>
                            <li class="collection-item">Duration: <b>{{ object.duration}}</b></li>
                            <li class="collection-item">
                                  <a href="">
                                   <span class="new badge blue"
                                         data-badge-caption="dislike">
                                      {{ object.dislike }} </span>
                                </a>
                                    <a href="{% url 'movie:like' object.id %}">
                                     <span class="new badge orange"
                                           data-badge-caption="like">
                                         {{ object.like }}</span>
                                </a>

                            </li>
                          </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}